### ISSUE TITLE
Allow `open-ce get licenses` to work with existing conda environments

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce-builder#103]
It might be useful to let the `open-ce get licenses` command work with existing conda environments instead of only requiring a conda environment file. This would remove an extra step that a user might need to take of creating a conda environment file. A simple way of doing this would be to automatically generate a conda environment file when a user passes in a conda environment name and pass this to the `open-ce get licenses` command.

**Comment by alexlang74** [comment]
No intent to address this enhancement right now
