### ISSUE TITLE
[REQUEST] Build With System MPI

### ISSUE THREAD

**Issue by bethune-bryant** [open-ce/open-ce-builder#104]
**Describe the solution you'd like**
Currently the builder provides the `--mpi_type system` variant flag to build with the system MPI.

The goal of that was primarily to allow users to build with a system installation of spectrum MPI.

However, on some systems there is an issue where the mpi compilers can't be found when build Horovod.

**Describe alternatives you've considered**
Passing through the the MPI_DIR env var used to work, but no longer does.
https://github.com/open-ce/horovod-feedstock/pull/23

Now we are just disabling the conda compilers when using system MPI, but that's not ideal.
https://github.com/open-ce/horovod-feedstock/pull/28

**Additional context**

**Comment by alexlang74** [comment]
No intent to fix right now
