### ISSUE TITLE
[BUG] switch to using CLI commands instead of API

### ISSUE THREAD

**Issue by cdeepali** [open-ce/open-ce-builder#117]
Looks like CLI commands work better compared to the APIs, so better to switch to using CLI commands in code. - https://github.com/conda/conda-build/issues/4228#issuecomment-1069478592

**Comment by alexlang74** [comment]
To be investigated in Q2 '22, as part of OpenCE 1.7 release cycle...

**Comment by cdeepali** [comment]
This issue is resolved.
