### ISSUE TITLE
Remove open-ce-builder version from generated image names

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce-builder#15]
When using the `build image` command, the open-ce-builder version is being added to the image name. Instead, we would like the `--git_tag_for_env` value that was used to create the conda environment file added to the image name. This value can be saved as a comment within the generated conda environment files.

**Comment by npanpaliya** [comment]
@bnemanich - for main branch builds where --git_tag_for_env is set to `None`, should we add `latest` in the conda env files, so that the runtime image name will be something like `open-ce:latest-py3.7-cpu-openmpi-10.2`?

**Comment by bnemanich** [comment]
Yeah, I think that makes sense.

**Comment by bethune-bryant** [comment]
Fixed in #26
