### ISSUE TITLE
Reduce size of built images

### ISSUE THREAD

**Issue by bnemanich** [open-ce/open-ce-builder#5]
Images coming out of the `open-ce build image` command can be very large since they include copies of the generated channel. There is also a `chown` command on the channel which is doubling the size.

For this issue, determine if there is a way to create the image without including the channel at all in the final image. Newer versions of docker or podman might be needed to accomplish this.

**Comment by npanpaliya** [comment]
There could be some ways to minimize the problem -
1. If we could upload the packages from local conda channel to some place and download them using wget in the Dockerfile, it would be much easier
2. If we copy the compressed local conda channel to the image, and then add a script to the image, which on the entrypoint would untar the channel and create conda environment from it.
3. Use COPY --chown option or docker build --squash option. But using these options need newer versions of docker/podman. Moreover, squash option has its own limitations too.

**Comment by npanpaliya** [comment]
Another problem that I see is about build context. Currently BUILD CONTEXT used is `.` means current directory is set as the build context and most of the stuff in the current directory except the directory being copied (local conda channel) is unwanted. So, I think changing build context to some other directory will also help in minimizing the size and build time of docker image.

**Comment by npanpaliya** [comment]
I was just trying above thing to see how much improvement do we see. And then realized that compression isn't really necessary as the local conda channel itself contains all the tar.gz, so we won't get much benefit by compressing the local conda channel.
